### ISSUE TITLE
future_lapply() in future package is deprecated

### ISSUE THREAD

**Issue by tklebel** [ropensci/robotstxt#24]
`get_robotstxts("https://google.com", use_futures = T)` gives a warning with version `1.8.1` of `future`:

> The implementation of future_lapply() in the 'future' package has been deprecated. Please use the one in the 'future.apply' package instead.

**Comment by petermeissner** [comment]
Nice, thanks. ... Everything should work fine since it's only deprecated
not gone. I will look into this or appreciate a pull request.

Best, Peter

Thomas Klebel <notifications@github.com> schrieb am Mo., 14. Mai 2018,
16:46:

**Comment by tklebel** [comment]
Yep, just wanted to notify you of the warning. It seems to me that simply adding `future.apply` as an import and changing this line: https://github.com/ropenscilabs/robotstxt/blob/8b48acc7ccb617308e7ed288840fd7bdb76cc6d2/R/get_robotstxts.R#L61

should resolve the issue.
However, I'm not familiar with the futures package, and since those lines are not covered by a test, I'd rather not change it myself 🙃

**Comment by petermeissner** [comment]
:-)

Thomas Klebel <notifications@github.com> schrieb am Mo., 14. Mai 2018,
17:15:

**Comment by HenrikBengtsson** [comment]
FYI, I'm about to release future 1.9.0 where this will break with:

```r
checking re-building of vignette outputs ... WARNING
Error in re-building vignettes:
  ...
Quitting from lines 48-51 (using_robotstxt.Rmd) 
Error: processing vignette 'using_robotstxt.Rmd' failed with diagnostics:
The implementation of future_lapply() in the 'future' package is defunct. Please use the one in the 'future.apply' package instead.
Execution halted
```

**Comment by petermeissner** [comment]
Thanks, what's the timetable?

Henrik Bengtsson <notifications@github.com> schrieb am Sa., 7. Juli 2018,
16:58:

**Comment by HenrikBengtsson** [comment]
FYI, I'm getting ready to submit future 1.9.0 to CRAN.

**Comment by petermeissner** [comment]
Thank you all for letting me know - its adjusted and on CRAN.

**Comment by HenrikBengtsson** [comment]
Yes, thxs. And it now passes future's revdep tests - https://github.com/HenrikBengtsson/future/commit/9f67c57978526056dcc79b9602c155a7e365ec3e
