### ISSUE TITLE
transfer to ropensci

### ISSUE THREAD

**Issue by maelle** [ropensci/robotstxt#25]
:wave: @petermeissner! we no longer transfer onboarded packages to ropenscilabs but instead directly to ropensci so we should move this repo. Are you ok with my doing it? If so when would you have the time to update all links? I wouldn't transfer before you have time to do that, and it's not urgent to transfer anyway.

If possible could you please add this badge to the README of rnaturalearth when updating CI links?
`[![Project Status: Active – The project has reached a stable, usable state and is being actively developed.](http://www.repostatus.org/badges/latest/active.svg)](http://www.repostatus.org/#active)`

Thanks for your patience! 🙏

**Comment by petermeissner** [comment]
I am definitely more than ok with moving to ropensci.

- All links? From the Readme? 
- Something else?

I will look into this some day within the next week.

**Comment by maelle** [comment]
Cool thanks!

Only DESCRIPTION and README I think! ☺

**Comment by petermeissner** [comment]
Hey, sorry it took so long to come back on this - move it whenever you have time I shall be able to adjust links and the like within one day or less.

**Comment by maelle** [comment]
Transferred! And I made you admin (again?).

**Comment by maelle** [comment]
I've just added a few topics to the repo, please review.

**Comment by petermeissner** [comment]
Perfect, thanks for your efforts. 

All links in DESCRIPTION and README should be up to date. 

- so, I close this

**Comment by maelle** [comment]
Thanks! 😀
