### ISSUE TITLE
GOV.UK Crawl-delay

### ISSUE THREAD

**Issue by nacnudus** [ropensci/robotstxt#48]
Hi, thank you for this very handy package, which I learned about via https://github.com/dmi3kno/polite/.

I think there might be bug in the way `Crawl-delay` is parsed.  Here is GOV.UK's [`robots.txt`](https://www.gov.uk/robots.txt)

```
User-agent: *
Disallow: /*/print$
# Don't allow indexing of user needs pages
Disallow: /info/*
Sitemap: https://www.gov.uk/sitemap.xml
# https://ahrefs.com/robot/ crawls the site frequently
User-agent: AhrefsBot
Crawl-delay: 10
# https://www.deepcrawl.com/bot/ makes lots of requests. Ideally
# we'd slow it down rather than blocking it but it doesn't mention
# whether or not it supports crawl-delay.
User-agent: deepcrawl
Disallow: /
# Complaints of 429 'Too many requests' seem to be coming from SharePoint servers
# (https://social.msdn.microsoft.com/Forums/en-US/3ea268ed-58a6-4166-ab40-d3f4fc55fef4)
# The robot doesn't recognise its User-Agent string, see the MS support article:
# https://support.microsoft.com/en-us/help/3019711/the-sharepoint-server-crawler-ignores-directives-in-robots-txt
User-agent: MS Search 6.0 Robot
Disallow: /
```

Which `robotstxt` interprets as a `Crawl-delay` of 10 for everyone.

```r
robotstxt::robotstxt("https://www.gov.uk/")$crawl_delay
#>         field        useragent value
#> 1 Crawl-delay                *    10
#> 2 Crawl-delay        AhrefsBot    10
#> 3 Crawl-delay        deepcrawl    10
#> 4 Crawl-delay MSSearch6.0Robot    10
```

My interpretation is that no delay is specified for the `*` user-agent, and there is also no specific limit in GOV.UK's [guidance](https://www.gov.uk/help/reuse-govuk-content).

> You can scrape GOV.UK as long as you respect our robots.txt policy. If you make too many requests, your access will be limited until your request rate drops. This is known as rate limiting.

**Comment by petermeissner** [comment]
Thanks for reporting - confirmed with newest version of package.

**Comment by petermeissner** [comment]
**The robots.txt file is broken, the parser is right.**

See example here: https://support.google.com/webmasters/answer/6062596?hl=de&ref_topic=6061961

**Rules:**

- robots.txt files consist of blocks.
- blocks are separated by empty newlines
- blocks can have more than one `User-agent:` entry

**This way it would work:**

```
parse_robotstxt("
User-agent: *
Disallow: /*/print$

# Don't allow indexing of user needs pages
Disallow: /info/*
Sitemap: https://www.gov.uk/sitemap.xml

# https://ahrefs.com/robot/ crawls the site frequently
User-agent: AhrefsBot
Crawl-delay: 10

# https://www.deepcrawl.com/bot/ makes lots of requests. Ideally
# we'd slow it down rather than blocking it but it doesn't mention
# whether or not it supports crawl-delay.
User-agent: deepcrawl
Disallow: /

# Complaints of 429 'Too many requests' seem to be coming from SharePoint servers
# (https://social.msdn.microsoft.com/Forums/en-US/3ea268ed-58a6-4166-ab40-d3f4fc55fef4)
# The robot doesn't recognise its User-Agent string, see the MS support article:
# https://support.microsoft.com/en-us/help/3019711/the-sharepoint-server-crawler-ignores-directives-in-robots-txt
User-agent: MS Search 6.0 Robot
Disallow: /
")$crawl_delay

##         field useragent value
## 1 Crawl-delay AhrefsBot    10
```

➡️ **I am note sure I can do anything about files not conforming to standard.**

**Comment by dmi3kno** [comment]
@nacnudus looks like you need to file this issue with https://github.com/alphagov

**Comment by nacnudus** [comment]
@petermeissner There seem to be conflicting standards.  [Google's guidance](https://developers.google.com/search/reference/robots_txt) is that blank lines are optional, so there are probably many other files out there without blank lines.

> Note the optional use of white-space (an empty line) to improve readability.

[W3C](https://www.w3.org/TR/html4/appendix/notes.html#h-B.4.1.1) doesn't require empty lines, but doesn't permit them within records.

> Blank lines are not permitted within a single record in the "robots.txt" file.

Three standards on robotstxt.org that require empty lines:

[One](http://www.robotstxt.org/robotstxt.html)
> Note that you need a separate "Disallow" line for every URL prefix you want to exclude -- you cannot say "Disallow: /cgi-bin/ /tmp/" on a single line. Also, you may not have blank lines in a record, as they are used to delimit multiple records.

[Two](http://www.robotstxt.org/orig.html)
> The file consists of one or more records separated by one or more blank lines (terminated by CR,CR/NL, or NL).

[Three](http://www.robotstxt.org/norobots-rfc.txt)
> The format logically consists of a non-empty set or records, separated by blank lines.

**Comment by petermeissner** [comment]
I agree on the conflicting part. 

I am not sure though how it is possible to have multiple user-agents per record without using empty lines as delimiter. 😕 ❓ ... seems underdetermined to me or simply an error on googles part. 

All other references I find mention  that empty lines are not allowed within records/blocks and but can be used before user-agent entries to separate blocks.

**Comment by petermeissner** [comment]
also https://stackoverflow.com/questions/20294485/is-it-possible-to-list-multiple-user-agents-in-one-line

**Comment by petermeissner** [comment]
I think there can be a solution that will still work with 'sloppy' delimited and multi-user-agent records ...

**Comment by petermeissner** [comment]
With version 0.7.1 (the current head on master) this should work. 

@nacnudus please try out 💯

**Comment by nacnudus** [comment]
@petermeissner Brilliant, thank you!  Fwiw a fix is also in progress on GOV.UK.
