### ISSUE TITLE
Save cached/normal as attribute

### ISSUE THREAD

**Issue by dmi3kno** [ropensci/robotstxt#53]
As mentioned [on Twitter](https://twitter.com/dmi3k/status/1271191006302613504?s=20), you are making a check if cached version of robotstxt exists, but you never write this property into the object. 
https://github.com/ropensci/robotstxt/blob/41a1912939b37a6b596bf27e2166b41d816cdaa3/R/get_robotstxt.R#L62-L88
Could we please save/update it in the request object? I want to be able to tell whether I have fresh copy or a copy from cache in code (without turning on the verbose mode).

**Comment by petermeissner** [comment]
Sounds good -will do.

**Comment by petermeissner** [comment]
@dmi3kno Can you check if changes in https://github.com/ropensci/robotstxt/commit/e6cf2a23e99971d2045e0022549a1314361e4539 work for you or are there still things missing?.

**Comment by dmi3kno** [comment]
I see you closed it. I tested and if looks good thanks!
I rely on this functionality in my package now. I push to CRAN after you push to CRAN.
