### ISSUE TITLE
New Maintainer Wanted :-)

### ISSUE THREAD

**Issue by maelle** [ropensci/robotstxt#62]
Or new maintainer team. :smile_cat: 

If you're interested, please comment in the issue.
For more info, see
- [our guidance on Changing package maintainers](https://devguide.ropensci.org/changing-maintainers.html);
- [our Package Curation Policy](https://devguide.ropensci.org/curationpolicy.html).

**Comment by maelle** [comment]
@ropensci/admin

**Comment by pedrobtz** [comment]
I would like to contribute 👋

**Comment by maelle** [comment]
Thanks a ton @pedrobtz!

I've sent you an invitation to the GitHub organization and to a team with admin access with this repository. 
Note that you'll need to have enabled two-factor authentication for your GitHub account, see https://ropensci.org/blog/2022/05/16/requiring-2fa-for-the-ropensci-github-organization/

Please ping me (on GitHub, or `maelle@ropensci.org`) if you have any question.
You could also join our friendly Slack workspace where there is a #package-maintenance channel. 
What email address should we use to send you an invitation?

Please add yourself to the DESCRIPTION file with the role `c("aut", "cre")` and make the former maintainer just `"aut"` to officially register the maintainer change.

Thanks again and see you around!
