### ISSUE TITLE
CRAN package spiderbar and its reverse dependencies

### ISSUE THREAD

**Issue by petermeissner** [ropensci/robotstxt#68]
This came in via email ... 

<img width="308" alt="image" src="https://user-images.githubusercontent.com/939139/217367211-605698e5-bb91-4753-9fef-6b67d2cacdcb.png">

> Dear maintainers,
> 
> This concerns the CRAN packages
> 
>   cthist polite ralger robotstxt spiderbar
> 
> maintained by one of you:
> 
>   Benjamin Gregory Carlisle <[murph@bgcarlisle.com](mailto:murph@bgcarlisle.com)>: cthist
>   Bob Rudis <[bob@rud.is](mailto:bob@rud.is)>: spiderbar
>   Dmytro Perepolkin <[dperepolkin@gmail.com](mailto:dperepolkin@gmail.com)>: polite
>   Mohamed El Fodil Ihaddaden <[ihaddaden.fodeil@gmail.com](mailto:ihaddaden.fodeil@gmail.com)>: ralger
>   Peter Meissner <[retep.meissner@gmail.com](mailto:retep.meissner@gmail.com)>: robotstxt
> 
> We have asked for an update fixing the check problems shown at
>   <https://cran.r-project.org/web/checks/check_results_spiderbar.html>
> with no update from the maintainer thus far.
> 
> Thus, package spiderbar is now scheduled for archival on 2023-02-21,
> and archiving this will necessitate also archiving its CRAN strong
> reverse dependencies.
> 
> Please negotiate the necessary actions.
> 
> The CRAN Team

Link to the spiderbar package: https://github.com/hrbrmstr/spiderbar

**Comment by hrbrmstr** [comment]
Waiting on CRAN to click "approve"

**Comment by pedrobtz** [comment]
is there anything one should do from the `robotstxt` side?

**Comment by petermeissner** [comment]
Nope, I think we can close this @hrbrmstr made the update and it went through to CRAN. 

(@hrbrmstr , who is the best? You are the best!)

closing
